language: c
sudo: false
cache:
  directories:
    - ~/container
before_install:
 # As a special case for this project, copy all the shell scripts into
 # the container directory, so that we can use them directly.
 - mkdir -p ~/container/_scripts
 - rsync -r -u travis/* ~/container/_scripts/
 - export __POLYSQUARE_CI_SCRIPTS_BOOTSTRAP="~/container/_scripts/bootstrap.sh"
 - eval "$(bash ~/container/_scripts/bootstrap.sh -d ~/container -s setup/shell/setup.sh)"
 # For now
 - polysquare_task "Installing pandoc" polysquare_fatal_error_on_failure cabal install pandoc
script:
 - polysquare_fetch_and_exec check/shell/check.sh -d travis -d tests
 - bash travis/prepare-lang-cache.sh -d ~/container -l haskell -l python -l ruby -l node
