environment:
  matrix:
    - PYTHON: C:\Python34
    - PYTHON: C:\Python27

cache:
 - C:\container -> appveyor.yml

install:
 - ps: $env:PATH="${env:PYTHON};${env:PYTHON}\Scripts;C:\MinGW\bin;C:\Python34;C:\Python34\Scripts;C:\Ruby21\bin;${env:PATH}"
 - ps: python ciscripts/bootstrap.py -d C:/container -s container-setup.py -r $(pwd) -e powershell -p test-env.ps1 --no-mdl
 - ps: . ./test-env

build: false

test_script:
 - ps: polysquare_run check/python/check.py --coverage-exclude "*/__init__.py" "*/_scripts/*" "tmp*" --lint-exclude="*/sample/*" --no-mdl

after_test:
 - ps: polysquare_cleanup

